Tidy HTML structure
AnnaUlyanova/sprint-2 pull request #1
Opened 2016-10-05 03:45 UTC by AnnaUlyanova

Hey,

Did some formatting & indenting the HTML, based on advices from this link - https://www.granneman.com/webdev/coding/formatting-and-indenting-your-html/.

2016-10-06 23:11 UTC, JessicaNeary requested changes
Pretty good indention, just a couple lines that need adjusting. Adding more whitespace between items might be a good idea to make the code a bit clearer too.

2016-10-06 23:11 UTC, JessicaNeary commented on pristine-zen-garden.html
> +    </div>
this </div> tag needs to be indented more

2016-10-06 23:11 UTC, JessicaNeary commented on pristine-zen-garden.html
> +  <footer>
Footer needs to be indented one more space

2016-10-06 23:11 UTC, JessicaNeary commented on pristine-zen-garden.html
> +                        <abbr title="Cascading Style Sheets">CSS</abbr> Resources</a>
Second line of <a href> isn't in line with the start of the tag

2016-10-07 18:52 UTC, AnnaUlyanova commented on pristine-zen-garden.html
> +                        <abbr title="Cascading Style Sheets">CSS</abbr> Resources</a>
Hi Jessica, thanks for the review. I've corrected the indention followed all the comments. Please review again :) Thanks heaps!

2016-10-09 05:57 UTC, merged